image: docker:stable

stages:
  - build

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  only:
    - master
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -f Dockerfile -t ${CONTAINER_RELEASE_IMAGE} .
    - docker push ${CONTAINER_RELEASE_IMAGE}
  after_script:
    - docker logout ${CI_REGISTRY}
  stage: build
  tags:
    - docker