version: '3'

services:
  app:
    image: registry.routeam.ru/common/report-creator:latest
    volumes:
      - ./files:/files
      - ./.env:/.env
    ports:
      - 8001:8001
  test:
    build:
      context: ./
      dockerfile: ./tests/Dockerfile
    depends_on:
      - app