version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./files:/files
      - ./.env:/.env
    ports:
      - 8001:8001
  test:
    build:
      context: ./
      dockerfile: ./tests/Dockerfile
    depends_on:
      - app